name: test

on:
  push:
    branches: [ master, test ]
  pull_request:
    branches: [ master ]

jobs:
  test5:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        shell: powershell
        run: ./1.build.ps1 test

  test7:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        shell: pwsh
        run: ./1.build.ps1 test

  test2:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: boot
        shell: powershell
        run: ./1.build.ps1 ?
      - name: test
        shell: cmd
        run: powershell -Version 2 ./1.build.ps1 test
